export type kpFullFilmType = {
  kinopoiskId: number,
  kinopoiskHDId: string,
  imdbId: null | string ,
  nameRu: string,
  nameEn: null | string,
  nameOriginal: null | string,
  posterUrl: string,
  posterUrlPreview: string,
  coverUrl: string,
  logoUrl: null | string,
  reviewsCount: number,
  ratingGoodReview: number,
  ratingGoodReviewVoteCount: number,
  ratingKinopoisk: number,
  ratingKinopoiskVoteCount: number,
  ratingImdb: number,
  ratingImdbVoteCount: number,
  ratingFilmCritics: null | string,
  ratingFilmCriticsVoteCount: number,
  ratingAwait: number,
  ratingAwaitCount: number,
  ratingRfCritics: number,
  ratingRfCriticsVoteCount: number,
  webUrl: string,
  year: number,
  filmLength: number,
  slogan: null | string,
  description: string,
  shortDescription: string,
  editorAnnotation: null | string,
  isTicketsAvailable: boolean,
  productionStatus: null | string,
  type: string,
  ratingMpaa: null | string,
  ratingAgeLimits: string,
  countries: Array<{country: string}>,
  genres: Array<{genre: string}>,
  startYear: null | number,
  endYear: null | number,
  serial: boolean,
  shortFilm: boolean,
  completed: boolean,
  hasImax: boolean,
  has3D: boolean,
  lastSync: string,
}


export type kpFilmType = {
     kinopoiskId : number,
     nameRu : string,
     nameEn :  string,
     nameOriginal?:  string,
     year : number,
     posterUrl:  string,
     posterUrlPreview : string,
     countries: Array<{country :  string}>,
     genres: Array<{genre:  string}>,
     duration : number,
     premiereRu :  string 
}


